# Action Panel respositioning on window resize and on load to move it from the right side to the top middle.

$(document).ready ->
  if $(window).width() < 1000
    $('#action_panel_top').appendTo '#action_panel_mstop'
    $('#page_info_card').appendTo '#page_info_mscard'
    $('#action_panel_file').appendTo '#action_panel_msfile'
    $('#action_panel_review').appendTo '#action_panel_msfile'
    $('#profile_cs').appendTo '#profile_cs_ms'
    $('#profile_pi').appendTo '#profile_pi_ms'
    $('#profile_badge').appendTo '#profile_badge_ms'
    $('#profile_acc').appendTo '#profile_acc_ms'
    $('#city_cs').appendTo '#city_ms_cs'
    $('#city_pi').appendTo '#city_pi_ms'
    $('#city_add').appendTo '#city_add_ms'
    $('#city_start').appendTo '#city_start_ms'
    $('#ms_ap_content').css 'display', 'block'
    $('#non_ms_ap_content').css 'display', 'none'
  else
    $('#action_panel_top').appendTo '#action_panel_org'
    $('#page_info_card').appendTo '#page_info_card_org'
    $('#action_panel_file').appendTo '#action_panel_org'
    $('#action_panel_review').appendTo '#action_panel_org'
    $('#profile_cs').appendTo '#profile_cs_org'
    $('#profile_pi').appendTo '#profile_pi_org'
    $('#profile_badge').appendTo '#profile_badge_org'
    $('#profile_acc').appendTo '#profile_acc_org'
    $('#city_cs').appendTo '#city_cs_org'
    $('#city_pi').appendTo '#city_pi_org'
    $('#city_add').appendTo '#city_add_org'
    $('#city_start').appendTo '#city_start_org'
    $('#ms_ap_content').css 'display', 'none'
    $('#non_ms_ap_content').css 'display', 'block'
  return
$(window).resize ->
  if $(window).width() < 1000
    $('#action_panel_top').appendTo '#action_panel_mstop'
    $('#page_info_card').appendTo '#page_info_mscard'
    $('#action_panel_file').appendTo '#action_panel_msfile'
    $('#action_panel_review').appendTo '#action_panel_msfile'
    $('#profile_cs').appendTo '#profile_cs_ms'
    $('#profile_pi').appendTo '#profile_pi_ms'
    $('#profile_badge').appendTo '#profile_badge_ms'
    $('#profile_acc').appendTo '#profile_acc_ms'
    $('#city_cs').appendTo '#city_ms_cs'
    $('#city_pi').appendTo '#city_pi_ms'
    $('#city_add').appendTo '#city_add_ms'
    $('#city_start').appendTo '#city_start_ms'
    $('#ms_ap_content').css 'display', 'block'
    $('#non_ms_ap_content').css 'display', 'none'
  else
    $('#action_panel_top').appendTo '#action_panel_org'
    $('#page_info_card').appendTo '#page_info_card_org'
    $('#action_panel_file').appendTo '#action_panel_org'
    $('#action_panel_review').appendTo '#action_panel_org'
    $('#profile_cs').appendTo '#profile_cs_org'
    $('#profile_pi').appendTo '#profile_pi_org'
    $('#profile_badge').appendTo '#profile_badge_org'
    $('#profile_acc').appendTo '#profile_acc_org'
    $('#city_cs').appendTo '#city_cs_org'
    $('#city_pi').appendTo '#city_pi_org'
    $('#city_add').appendTo '#city_add_org'
    $('#city_start').appendTo '#city_start_org'
    $('#ms_ap_content').css 'display', 'none'
    $('#non_ms_ap_content').css 'display', 'block'
  return